filepaths:
  delphi_repo:
    omar: C:/Users/omars/Desktop/covid19_dimitris/DELPHI/
    michael: I:/DELPHI/
    michael2: E:/Github/DELPHI/
    hamza: /Users/hamzatazi/Desktop/MIT/999.1 Research Assistantship/4. COVID19_Global/DELPHI/
    saksham: D:/COVID19/DELPHI/
    saksham2: /Users/saksham/Research/COVIDAnalytics/DELPHI/
  data_sandbox:
    omar: C:/Users/omars/Desktop/covid19_dimitris/DELPHI/data_sandbox/
    michael: I:/DELPHI/data_sandbox/
    michael2: E:/Github/DELPHI/data_sandbox/
    hamza: /Users/hamzatazi/Desktop/MIT/999.1 Research Assistantship/4. COVID19_Global/DELPHI/data_sandbox/
    saksham: D:/COVID19/DELPHI/data_sandbox/
    saksham2: /Users/saksham/Research/COVIDAnalytics/DELPHI/data_sandbox/
  danger_map:
    omar: C:/Users/omars/Desktop/covid19_dimitris/covid19orc/danger_map/
    michael: I:/covid19orc/danger_map/
    michael2:  E:/Github/covid19orc/danger_map/
    hamza: /Users/hamzatazi/Desktop/MIT/999.1 Research Assistantship/4. COVID19_Global/covid19orc/danger_map/
    saksham: D:/COVID19/covid19orc/danger_map/
    saksham2: /Users/saksham/Research/COVIDAnalytics/covid19orc/danger_map/
  website:
    omar: C:/Users/omars/Desktop/covid19_dimitris/website/
    michael: I:/website/
    michael2:  E:/Github/website/
    hamza: /Users/hamzatazi/Desktop/MIT/999.1 Research Assistantship/4. COVID19_Global/website/
    saksham: D:/COVID19/website/
    saksham2: /Users/saksham/Research/COVIDAnalytics/website/
  logs:
    omar: C:/Users/omars/Desktop/covid19_dimitris/DELPHI/logs/
    michael: I:/DELPHI/logs/
    michael2: E:/Github/DELPHI/logs/
    hamza: /Users/hamzatazi/Desktop/MIT/999.1 Research Assistantship/4. COVID19_Global/DELPHI/logs/
    saksham: D:/COVID19/DELPHI/logs/
    saksham2: /Users/saksham/Research/COVIDAnalytics/DELPHI/logs/
